default:
  just --list

# Run the npm dev server
srv_dev:
    # python3 -m http.server 8005
    # python3 ../ci_scripts/webserver_multithread_policy.py -p 8005
    npm run dev


gpt_files_content:
    for f in $(cat f.txt); do echo "===========================================================================";echo "File $f"; echo "==========================================================================="; echo '```'; cat $f; echo '```'; done

# Create a json version of the table of content (for Single Page HTML)
tutorial-json_toc:
    python scripts/convert_toc.py

tutorial_book:
    jupyter-book build .

tutorial_book_pdf:
    jupyter-book build --builder pdfhtml .

