include::_utils.adoc[]

[[assets_about]]
== Assets

HelloImGui and ImmApp applications rely on the presence of an `assets` folder.

**This folder stores**

* All the resources (images, fonts, etc.) used by the application. Feel free to add any resources there!
* The application settings (e.g. the app icon, the app settings for macOS and iOS, etc.)

**Assets folder location**

* **Python**: Place the assets folder in the same folder as the script
* **{cpp}**: The assets folder should be placed in the same folder as the CMakeLists.txt for the application (the one calling `imgui_bundle_add_app`)


**Typical layout of the assets folder**

[source,bash]
----
assets/
    +-- app_settings/                # Application settings
    |    +-- icon.png                # This will be the app icon, it should be square
    |    |                           # and at least 256x256. It will  be converted
    |    |                           # to the right format, for each platform (except Android)
    |    +-- apple/
    |    |         +-- Info.plist    # macOS and iOS app settings
    |    |                           # (or Info.ios.plist + Info.macos.plist)
    |    |
    |    +-- android/                # Android app settings: files here will be deployed
    |    |   |-- AndroidManifest.xml # Optional manifest
    |    |   +-- res/
    |    |       +-- mipmap-xxxhdpi/ # Optional icons for different resolutions
    |    |           +-- ...         # Use Android Studio to generate them:
    |    |                           # right click on res/ => New > Image Asset
    |    +-- emscripten/
    |      |-- shell.emscripten.html # Emscripten shell file
    |      |                         #   (this file will be cmake "configured"
    |      |                         #    to add the name and favicon)
    |      +-- custom.js             # Any custom file here will be deployed
    |                                #   in the emscripten build folder

    +-- fonts/
    |    +-- DroidSans.ttf            # Default fonts used by HelloImGui to
    |    +-- fontawesome-webfont.ttf  # improve text rendering (esp. on High DPI)
    |    |                            # if absent, a default LowRes font is used.
    |    |
    |    +-- Roboto/                  # Optional: fonts for markdown
    |         +-- LICENSE.txt
    |         +-- Roboto-Bold.ttf
    |         +-- Roboto-BoldItalic.ttf
    |         +-- Roboto-Regular.ttf
    |         +-- Roboto-RegularItalic.ttf
    |         +-- Inconsolata-Medium.ttf
    +-- images/
         +-- markdown_broken_image.png  # Optional: used for markdown
         +-- world.png                  # Add anything in the assets folder!
----

**If needed, change the assets folder location:**

* **Python**: Call `hello_imgui.set_assets_folder()` at startup.
* **{cpp}**: Call `HelloImGui::SetAssetsFolder` at startup. Or specify its location in CMake via `imgui_bundle_add_app(app_name file.cpp ASSETS_LOCATION "path/to/assets")`.


**Where to find the default assets**

You can link:https://traineq.org/ImGuiBundle/assets.zip[download the default assets as a zip file].

Look at the folder link:https://github.com/pthom/imgui_bundle/tree/main/bindings/imgui_bundle/assets[imgui_bundle/bindings/imgui_bundle/assets] to see their content.


include::assets_demo.adoc[]



=== App icon and app settings ({cpp} only)

_The assets folder is deployed automatically during the build; so that they are available automatically whatever the platform._


==== App icon
The app icon is defined by the file `icon.png` in the `assets/app_settings` folder. It should be square and at least 256x256 (but 512x512 is preferred).

`icon.png` will define the application icon as well as the window icon. It will be converted to the right format for each platform by CMake (via `imgui_bundle_add_app`).


See link:{url-bundle-doc-tree}/bindings/imgui_bundle/demos_python/demo_packaging[this demo] for an example showing how to package a python application.

==== App settings

**macOS and iOS**

The app settings are defined by the file `Info.plist` in the `assets/app_settings/apple` folder.

You can copy and edit this link:{url-bundle-doc-tree}/bindings/imgui_bundle/assets/app_settings/apple/Info.plist[example] by adding your own settings (replace `${HELLO_IMGUI_BUNDLE_XXX}` by your own values).

You can also specify different settings for macOS and iOS via `Info.macos.plist` and `Info.ios.plist`
