[[install_cpp]]
== Install for {cpp}


include::_utils.adoc[]

=== Integrate Dear ImGui Bundle in your own project in 5 minutes

The easiest way to use Dear ImGui Bundle in an external project is to use the template available at link:https://github.com/pthom/imgui_bundle_template[https://github.com/pthom/imgui_bundle_template].

This template includes everything you need to set up your own project.

=== Build from source

If you choose to clone this repo, follow these instructions:

[source, bash]
----
git clone https://github.com/pthom/imgui_bundle.git
cd imgui_bundle
git submodule update --init --recursive # <1>
mkdir build
cd build
cmake .. -DIMMVISION_FETCH_OPENCV=ON # <2>
make -j
----

<1> Since there are lots of submodules, this might take a few minutes
<2> The flag `-DIMMVISION_FETCH_OPENCV=ON` is optional. If set, a minimal version of OpenCV will be downloaded a compiled at this stage (this might require a few minutes)

****
The `immvision` module will only be built if OpenCV can be found. Otherwise, it will be ignored, and no error will be emitted.

If you have an existing OpenCV install, set its path via:
[source, bash]
----
cmake .. -DOpenCV_DIR=/.../path/to/OpenCVConfig.cmake
----
****

=== Run the {cpp} demo

If you built ImGuiBundle from source, Simply run `build/bin/demo_imgui_bundle`.


The source for the demos can be found inside link:{url-bindings-bundle}/demos_cpp/[bindings/imgui_bundle/demos_cpp].


TIP: Consider `demo_imgui_bundle` as a manual with lots of examples and related code source. It is always {url-demo-imgui-bundle}[available online]
