[[install_python]]
== Install for Python

include::_utils.adoc[]

=== Install from pypi

[source, bash]
----
pip install imgui-bundle  # <1>
pip install opencv-python # <2>
pip install pyGLM # <3>
----
<1> imgui_bundle: Binary wheels are available for Windows, MacOS and Linux. If a compilation from source is needed, the build process might take up to 5 minutes, and will require an internet connection.

<2> OpenCV: in order to run the immvision module, install opencv-python. The alternative OpenCV versions, such as opencv-python-headless (headless) opencv-contrib-python (with extra modules)  also work.

<3> pyGLM: in order to run the demo, install pyGLM

*Platform notes*

* _Windows_: Under windows, you might need to install https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170#visual-studio-2015-2017-2019-and-2022[msvc redist].
* _macOS_ : under macOS, if a binary wheel is not available (e.g. for older macOS versions), pip will try to compile from source. This might fail if you do not have XCode installed. In this case, install imgui-bundle with the following command `SYSTEM_VERSION_COMPAT=0 pip install --only-binary=:all: imgui_bundle`

=== Install from source
[source, bash]
----
git clone https://github.com/pthom/imgui_bundle.git
cd imgui_bundle
git submodule update --init --recursive # <1>
pip install -v . # <2>
pip install opencv-python
pip install pyGLM
----
<1> Since there are lots of submodules, this might take a few minutes
<2> The build process might take up to 5 minutes

=== Run the python demo

Simply run `demo_imgui_bundle`.

The source for the demos can be found inside link:{url-bindings-bundle}/demos_python[bindings/imgui_bundle/demos_python].


TIP: Consider `demo_imgui_bundle` as an always available manual for Dear ImGui Bundle with lots of examples and related code source.
