=== Usage with C++

include::_utils.adoc[]

==== Integrate ImGui Bundle in your own project in 5 minutes

The easiest way to use ImGui Bundle in an external project is to use the example provided in link:{url-bundle-main-tree}/_example_integration[example_integration].
This folder  includes everything you need to set up your own project with ImGui Bundle.

==== Build ImGui Bundle from source

If you choose to clone this repo, follow these instructions:

[source, bash]
----
git clone https://github.com/pthom/imgui_bundle.git
cd imgui_bundle
git submodule update --init --recursive # <1>
mkdir build
cd build
cmake ..
make -j # <2>
----

<1> Since there are lots of submodules, this might take a few minutes
<2> The build process might take up to 5 minutes

==== Run the C++ demo

If you built ImGui Bundle from source, Simply run `build/bin/demo_imgui_bundle`.


The source for the demos can be found inside link:{url-bindings-bundle}/demos_cpp/[bindings/imgui_bundle/demos_cpp].


TIP: Consider `demo_imgui_bundle` as a manual with lots of examples and related code source. It is always {url-demo-imgui-bundle}[available online]
