=== ImmApp - Immediate App

include::_utils.adoc[]


ImGui Bundle includes a library named ImmApp (which stands for Immediate App). ImmApp is a thin extension of HelloImGui that enables to easily initialize the ImGuiBundle addons that require additional setup at startup

==== API

{url-bundle-doc-tree}/external/immapp/immapp/runner.h[{cpp} API]

{url-bindings-bundle}/immapp/immapp_cpp.pyi[Python bindings]


==== How to start an application with addons


.Click to see an example application with addons
[%collapsible]
====

Some libraries included by ImGui Bundle require an initialization at startup. ImmApp makes this easy via AddOnParams.

The example program below demonstrates how to run an application which will use implot (which requires a context to be created at startup), and imgui_md (which requires additional fonts to be loaded at startup).

{cpp}
[source, cpp]
----
include::../../demos_cpp/demos_immapp/demo_implot_markdown.cpp[]
----

Python:
[source, python]
----
include::../../demos_python/demos_immapp/demo_implot_markdown.py[]
----

====
