=== Hello ImGui - Starter pack

include::_utils.adoc[]

Dear ImGui Bundle includes https://github.com/pthom/hello_imgui[Hello ImGui], which is itself based on ImGui. "Hello ImGui" can be compared to a starter pack that enables to easily write cross-platform Gui apps for Windows, macOS, Linux,  iOS,  and https://en.wikipedia.org/wiki/Emscripten[emscripten].

==== API & Usage

See the "Hello ImGui" https://pthom.github.io/hello_imgui/book/doc_api.html[API doc] and https://pthom.github.io/hello_imgui/book/doc_params.html[Application parameter doc].

==== Features

**Multiplatform utilities**

* Truly multiplatform: Linux, Windows, macOS, iOS, Android, emscripten (with 4 lines of CMake code)
* Easily embed assets on all platforms (no code required)
* Customize app settings (icon and app name for mobile platforms, etc.- no code required)
* Customize application icon on all platforms (including mobile and macOS - no code required)

**Dear ImGui Tweaks**

* Power Save mode: reduce FPS when idling
* High DPI support: scale UI according to DPI, whatever the platform
* Advanced layout handling: dockable windows, multiple layouts
* Window geometry utilities: autosize application window, restore app window position
* Theme tweaking: extensive list of additional themes
* Support for movable and resizable borderless windows
* Advanced font support: icons, emojis and colored fonts
* Integration with ImGui Test Engine: automate and test your apps
* Save user settings: window position, layout, opened windows, theme, user defined custom settings
* Easily add a custom 3D background to your app

**Backends**

* Available platform backends: SDL2, Glfw3
* Available rendering backends: OpenGL3, Metal, Vulkan, DirectX

NOTE: The usage of `Hello ImGui` is optional. You can also build an imgui application from scratch, in {cpp} or in python (see link:{url-bindings-bundle}/demos_python/demos_immapp/imgui_example_glfw_opengl3.py[python example])

TIP: HelloImGui is fully configurable by POD (plain old data) structures. See link:https://pthom.github.io/hello_imgui/book/doc_params.html[their description]

==== Advanced layout and theming with Hello ImGui:

See the demo named "demo_docking", which demonstrates:

* How to handle complex layouts: you can define several layouts and switch between them:  each layout which will remember the user modifications and the list of opened windows
* How to use theming
* How to store you own user settings in the app ini file
* How to add a status bar and a log window
* How to reduce the FPS when idling (to reduce CPU usage)

Links:

* see link:{url-bundle}/blob/main/bindings/imgui_bundle/demos_python/demos_immapp/demo_docking.py[demo_docking.py]
* see link:{url-bundle}/blob/main/bindings/imgui_bundle/demos_cpp/demos_immapp/demo_docking.cpp[demo_docking.cpp]
* link:https://traineq.org/ImGuiBundle/emscripten/bin/demo_docking.html[Run this demo online]
* see link:https://www.youtube.com/watch?v=XKxmz__F4ow[a short video explanation about layouts] on YouTube
