[[devdoc_pypi]]
== Pypi bundle package distribution

In order to create a new version,

1. Modify the version number in link:../setup.py[setup.py] and link:../CMakeLists.txt[CMakeList.txt]
2. Create a release on GitHub, and give it a new tag (e.g. `v0.8.3`)
   Wheels will be uploaded to pypi
3. Manually build and upload the macOS_arm64 wheel:

NOTE: the wheel build on an Intel Mac may try and fail to load Intel iPPIcv), this is why it shall be built on an M1 Mac.

=== Build / Mac arm64 via cibuildwheel

```
rm -rf _skbuild
CIBW_ARCHS_MACOS="arm64" pipx run cibuildwheel --platform=macos && say "wheel build finished"

twine upload wheelhouse/*
```

or
```
CIBW_ARCHS_MACOS="arm64" CIBW_BUILD="cp311-* cp312-*"  pipx run cibuildwheel --platform=macos
```

==== In order to build for Mac OS 11: disable freetype
1. Inside pyproject.toml, change the following line:
    environment = { MACOSX_DEPLOYMENT_TARGET="14.0" }
to
    environment = { MACOSX_DEPLOYMENT_TARGET="11.0" }
2. Disable freetype in main CMakeLists.txt, by changing the following line:

   # if(ANDROID OR MINGW)  # Change this line to the following
   if(ANDROID OR MINGW OR IMGUI_BUNDLE_BUILD_PYTHON)
      set(freetype_default OFF)
   endif()


=== Build and deploy to pypi via twine (obsolete)

```
python3 -m build --wheel  --sdist .
python3 -m build --sdist .

# or
python3 -m build  .

# then

twine upload dist/*
```

login = __token__
password = ...api_token...
