name: "Emscripten"

on:
  workflow_dispatch:
  pull_request:
  push:


jobs:
  build:
    name: Emscripten
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

#      - name: Setup interactive tmate session
#        uses: mxschmitt/action-tmate@v3

      - name: Build and install
        shell: bash
        run: |
          ./external/hello_imgui/hello_imgui/tools/emscripten/install_emscripten.sh
          mkdir build_ems
          cd build_ems
          source ~/emsdk/emsdk_env.sh
          emcmake cmake .. -DCMAKE_BUILD_TYPE=Release
          make -j 4
