=== How to integrate Dear ImGui Bundle into your {cpp} application

This directory is a *standalone* demonstration on how to easily integrate ImGuiBundle to your own project. This means that you can copy-paste the content folder in your project, and it will build, with no extra step!

link:https://traineq.org/ImGuiBundle/_example_integration.zip[Download this folder as a zip file]

NOTE: With this simple mode, you do not need to add `ImGui Bundle` as a submodule, or to install it. CMake will automatically fetch it and link your app with it!


==== CMake

The link:CMakeLists.txt[CMakeLists.txt] file

* Downloads imgui_bundle at configure time
* Makes the `imgui_bundle_add_app` cmake function available
* Uses `imgui_bundle_add_app` to build your app and link it with ImGuiBundle

_Note: imgui_bundle_add_app will automatically link your app to imgui_bundle, and will embed the assets folder (for desktop, mobile, and emscripten apps)_


==== Assets

Anything in the assets/ folder located beside the app's CMakeLists will be bundled together with the app (for macOS, iOS, Android, Emscripten).

The files in assets/app_settings/ will be used to generate the app icon, and the app settings (for macOS, iOS, Android).

[source]
----
assets/
├── world.jpg                         # A custom asset
├── app_settings/                     # Application settings
│         ├── icon.png                # This will be the app icon, it should be square
│         │                           # and at least 512x512. It will  be converted
│         │                           # to the right format, for each platform.
│         ├── apple/
│         │         └── Info.plist    # macOS and iOS app settings
│         │                          # (or Info.ios.plist + Info.macos.plist)
├── fonts/
│         ├── DroidSans.ttf           # Default fonts
│         └── fontawesome-webfont.ttf #     used by HelloImGui
│         ├── Roboto
│         │         ├── Roboto-Bold.ttf        # Font used by Markdown
│         │         ├── Roboto-BoldItalic.ttf
│         │         ├── Roboto-Regular.ttf
│         │         └── Roboto-RegularItalic.ttf
│         ├── SourceCodePro-Regular.ttf
├── images
│         └── markdown_broken_image.png

----


==== Main cpp file

The link:hello_world.cpp[hello_world.cpp] file

* Provides a Gui function which is executed at each frame
* Provides a main function that set the ImmApp ("Immediate App") params, and mentions the addons we intend to use (here we are using markdown and implot).
