=== How to use integrate ImGuiBundle into your application

This directory is a **standalone** demonstration on how to easily integrate ImGuiBundle to your own project. This means that you can copy-paste this folder in your project, and it will build, with no extra step!

TIP: you do *not* need to clone or download `ImGui Bundle`. It will be done by cmake automatically.

.Click to see CMakeLists.txt content
[%collapsible]
====
The link:CMakeLists.txt[CMakeLists.txt] file will

* download imgui_bundle at configure time
* make the `imgui_bundle_add_app` cmake function available
* use `imgui_bundle_add_app` to build your app and link it with ImGuiBundle

[source, cmake]
----
include::CMakeLists.txt[]
----
====

.Click to see hello_world.cpp content
[%collapsible]
====
The link:hello_world.cpp[hello_world.cpp] file

* Provides a Gui function which is executed at each frame
* Provides a main function that set the ImmApp ("Immediate App") params, and mentions the addons we intend to use (here we are using markdown and implot).

[source, cpp]
----
include::hello_world.cpp[]
----
====
