"""ImCoolbar: A Cool bar for Dear ImGui
Python bindings for https://github.com/aiekick/ImCoolBar
"""

###############################################################################
# This file is a part of Dear ImGui Bundle, NOT a part of ImCoolBar
# -----------------------------------------------------------------------------
# im_cool_bar.pyi: auto-generated bindings for ImCoolBar.
#
# Most of the code of this file is automatically generated (using https://pthom.github.io/litgen/),
# and is generally very close to the C++ version. Comments, docs are identical.
# Do not manually edit the autogenerated parts (look for "Autogenerated" comments)!
###############################################################################
# ruff: noqa: B008
import enum
from typing import Optional
from imgui_bundle.imgui import ImVec2, ImVec2Like, WindowFlags, WindowFlags_

ImCoolBarFlags = int
ImGuiWindowFlags = WindowFlags
ImGuiWindowFlags_None = WindowFlags_.none

# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  AUTOGENERATED CODE !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# <litgen_stub> // Autogenerated code below! Do not edit!
####################    <generated_from:ImCoolbar.h>    ####################
#
#MIT License
#
#Copyright (c) 2024-2026 Stephane Cuillerdier (aka Aiekick)
#
#Permission is hereby granted, free of charge, to any person obtaining a copy
#of this software and associated documentation files (the "Software"), to deal
#in the Software without restriction, including without limitation the rights
#to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
#copies of the Software, and to permit persons to whom the Software is
#furnished to do so, subject to the following conditions:
#
#The above copyright notice and this permission notice shall be included in all
#copies or substantial portions of the Software.
#
#THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
#SOFTWARE.
#


# ImCoolBar, v1.0.0
# macOS Dock-style magnification bar for Dear ImGui




class ImCoolBarFlags_(enum.IntEnum):
    #
    none = enum.auto()       # (= 0)
    horizontal = enum.auto() # (= (1 << 0))
    vertical = enum.auto()   # (= (1 << 1))

# #ifdef __cplusplus
#



# #define ENABLE_IMCOOLBAR_DEBUG


class ImCoolBarSettings:
    anchor: ImVec2 = ImVec2(0.5, 0.5)
    normal_size: float = float(40.0)
    hovered_size: float = float(150.0)
    anim_step: float = float(0.05)
    effect_strength: float = float(0.5)
    mode: ImCoolBarFlags = ImCoolBarFlags(ImCoolBarFlags_.horizontal)
    def __init__(
        self,
        a_anchor: Optional[ImVec2Like] = None,
        a_normal_size: float = 40.0,
        a_hovered_size: float = 150.0,
        a_anim_step: float = 0.05,
        a_effect_strength: float = 0.5,
        a_mode: Optional[ImCoolBarFlags] = None
        ) -> None:
        """Python bindings defaults:
            If any of the params below is None, then its default value below will be used:
                * aAnchor: ImVec2(0.5, 0.5)
                * aMode: ImCoolBarFlags_.horizontal
        """
        pass


def cool_bar_debug_check_version(a_version: str, a_settings_size: int) -> bool:
    pass
def begin_cool_bar(
    a_label: str,
    ar_settings: Optional[ImCoolBarSettings] = None,
    a_win_flags: Optional[ImGuiWindowFlags] = None
    ) -> bool:
    """Python bindings defaults:
        If any of the params below is None, then its default value below will be used:
            * arSettings: initialized with default value
            * aWinFlags: WindowFlags_.none
    """
    pass
def end_cool_bar() -> None:
    pass
def cool_bar_item() -> bool:
    pass
def get_cool_bar_item_width() -> float:
    pass
def get_cool_bar_item_scale() -> float:
    pass
def show_cool_bar_metrics(apo_open: bool) -> None:
    pass
def show_cool_bar_demo_window(
    apo_open: Optional[bool] = None,
    apo_settings: Optional[ImCoolBarSettings] = None,
    apo_default_settings: Optional[ImCoolBarSettings] = None
    ) -> None:
    pass



# #endif

#///////////////////////////////////////////////
#// C LANG API ///////////////////////////////
#/////////////////////////////////////////////

# #ifdef __cplusplus
#
# #else
# #endif


####################    </generated_from:ImCoolbar.h>    ####################

# </litgen_stub> // Autogenerated code end!
