"""imgui_microtex: native LaTeX math rendering via MicroTeX + FreeType."""

from typing import Optional, overload
import numpy as np
from imgui_bundle.imgui import ImVec4

ImU32 = int
ImTextureID = int


# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  AUTOGENERATED CODE !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# <litgen_stub> // Autogenerated code below! Do not edit!
####################    <generated_from:imgui_microtex.h>    ####################



# Public API for imgui_microtex: native LaTeX math rendering via MicroTeX + FreeType.
#
# Level 1: render LaTeX to an RGBA pixel buffer.
# Level 2: render LaTeX to an ImTextureID with caching.
#
# Thread safety: all functions are protected by a mutex and can be called from any thread.


# ============================================================================
# Initialization / shutdown
# ============================================================================

def init(clm_file: str, font_file: str) -> None:
    """ Initialize MicroTeX + FreeType backend.
     clmFile: path to the .clm1 font metrics file
     fontFile: path to the .otf font file
    """
    pass

def is_initialized() -> bool:
    """ Check if initialized."""
    pass

def release() -> None:
    """ Release all resources (including cached textures)."""
    pass

# ============================================================================
# Level 1: LaTeX -> RGBA pixel buffer
# ============================================================================

class RenderedFormula:
    width: int = 0
    height: int = 0
    depth: int = 0  # distance below baseline (in pixels)
    # Baseline: ratio of ascent to total height, in [0, 1].
    # To vertically align inline math with surrounding text of height textH:
    #   float yOffset = (Baseline - 1.0) * Height;
    #   ImGui::SetCursorPosY(ImGui::GetCursorPosY() - yOffset);
    baseline: float = 0
    def __init__(
        self,
        width: int = 0,
        height: int = 0,
        depth: int = 0,
        baseline: float = 0
        ) -> None:
        """Auto-generated default constructor with named params"""
        pass

    def pixels_as_array(self) -> np.ndarray:
        """Return pixels as a numpy array with shape (height, width, 4) in RGBA format.
        The returned array is a view into the internal buffer (no copy).
        """
        ...

# Render a LaTeX string to an RGBA pixel buffer.
# latex: the LaTeX math string (without $ delimiters)
# fontSize: font size in pixels
# color: foreground color (alpha channel is used)
@overload
def render(
    latex: str,
    font_size: float,
    color: Optional[ImU32] = None
    ) -> RenderedFormula:
    """Python bindings defaults:
        If color is None, then its default value will be: IM_COL32_BLACK
    """
    pass
@overload
def render(latex: str, font_size: float, color: ImVec4) -> RenderedFormula:
    pass

# ============================================================================
# Level 2: LaTeX -> ImTextureID (with caching)
# ============================================================================

class FormulaTexture:
    texture_id: ImTextureID = 0
    width: int = 0
    height: int = 0
    depth: int = 0
    # Baseline: ratio of ascent to total height, in [0, 1].
    # To vertically align inline math with surrounding text of height textH:
    #   float yOffset = (Baseline - 1.0) * Height;
    #   ImGui::SetCursorPosY(ImGui::GetCursorPosY() - yOffset);
    baseline: float = 0
    def __init__(
        self,
        texture_id: ImTextureID = 0,
        width: int = 0,
        height: int = 0,
        depth: int = 0,
        baseline: float = 0
        ) -> None:
        """Auto-generated default constructor with named params"""
        pass

# Render a LaTeX string to an ImGui texture (cached, 5 min TTL).
@overload
def render_to_texture(
    latex: str,
    font_size: float,
    color: Optional[ImU32] = None
    ) -> FormulaTexture:
    """Python bindings defaults:
        If color is None, then its default value will be: IM_COL32_BLACK
    """
    pass
@overload
def render_to_texture(latex: str, font_size: float, color: ImVec4) -> FormulaTexture:
    pass

def to_texture(formula: RenderedFormula) -> FormulaTexture:
    """ Convert a previously rendered formula to an ImGui texture (not cached)."""
    pass

def clear_texture_cache() -> None:
    """ Clear the texture cache."""
    pass


####################    </generated_from:imgui_microtex.h>    ####################

# </litgen_stub> // Autogenerated code end
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  AUTOGENERATED CODE END !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
