# Part of ImGui Bundle - MIT License - Copyright (c) 2022-2025 Pascal Thomet - https://github.com/pthom/imgui_bundle
# THIS FILE IS AUTOGENERATED — regenerate with external/imgui_manual/bindings/generate_imgui_manual.py
from __future__ import annotations
import enum
from typing import Optional

# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  AUTOGENERATED CODE !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# <litgen_stub> // Autogenerated code below! Do not edit!
####################    <generated_from:imgui_manual.h>    ####################

class ImGuiManualLibrary(enum.IntEnum):
    # ImGui,     /* original C++ signature */
    imgui = enum.auto()  # (= 0)
    # ImPlot,     /* original C++ signature */
    implot = enum.auto()  # (= 1)
    # ImPlot3D,     /* original C++ signature */
    implot3_d = enum.auto()  # (= 2)
    # ImAnim }    /* original C++ signature */
    im_anim = enum.auto()  # (= 3)

class ImGuiManualCppOrPython(enum.IntEnum):
    # Cpp,     /* original C++ signature */
    cpp = enum.auto()  # (= 0)
    # Python }    /* original C++ signature */
    python = enum.auto()  # (= 1)

# void ShowImGuiManualGui(std::optional<ImGuiManualLibrary> library = std::nullopt,    /* original C++ signature */
#                         std::optional<ImGuiManualCppOrPython> language = std::nullopt,
#                         bool show_status_bar = false);
def show_imgui_manual_gui(
    library: Optional[ImGuiManualLibrary] = None,
    language: Optional[ImGuiManualCppOrPython] = None,
    show_status_bar: bool = False,
) -> None:
    pass

####################    </generated_from:imgui_manual.h>    ####################

# </litgen_stub> // Autogenerated code end
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  AUTOGENERATED CODE END !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
