"""
"""

from typing import Tuple
import numpy as np
import enum

from imgui_bundle.hello_imgui import RunnerParams
from imgui_bundle.imgui_md import MarkdownOptions
from imgui_bundle.imgui_node_editor import Config as NodeEditorConfig


# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  AUTOGENERATED CODE !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# <litgen_stub> // Autogenerated code below! Do not edit!
####################    <generated_from:imgui_bundle.h>    ####################
def run(
    runner_params: HelloImGui.RunnerParams,
    with_implot: bool = False,
    with_node_editor: bool = False,
    with_node_editor_config: Optional[NodeEditorConfig] = None,
    with_markdown: bool = False,
    with_markdown_options: Optional[ImGuiMd.MarkdownOptions] = None,
) -> None:
    """Helper to run a hello_imgui app for imgui_bundle:

    - if `with_markdown` or `with_markdown_options` is specified, then  the markdown context will be initialized
        (i.e. required fonts will be loaded)
    - if `with_implot` is True, then a context for implot will be created/destroyed automatically
    - if `with_node_editor` or with_node_editor_config` is specified, then a context for imgui_node_editor
        will be created automatically.
    """
    pass

def run(
    gui_function: HelloImGui.VoidFunction,
    window_size: Optional[ImVec2] = None,
    window_title: Optional[str] = None,
    with_implot: bool = False,
    with_node_editor: bool = False,
    with_node_editor_config: Optional[NodeEditorConfig] = None,
    with_markdown: bool = False,
    with_markdown_options: Optional[ImGuiMd.MarkdownOptions] = None,
) -> None:
    """Helper to run a hello_imgui app for imgui_bundle:

    - if `with_markdown` or `with_markdown_options` is specified, then  the markdown context will be initialized
        (i.e. required fonts will be loaded)
    - if `with_implot` is True, then a context for implot will be created/destroyed automatically
    - if `with_node_editor` or with_node_editor_config` is specified, then a context for imgui_node_editor
        will be created automatically.
    """
    pass

def now() -> float:
    pass

def current_node_editor_context() -> ax.NodeEditor.EditorContext:
    pass
####################    </generated_from:imgui_bundle.h>    ####################

# </litgen_stub> // Autogenerated code end!
