###############################################################################
# This file is a part of Dear ImGui Bundle, NOT a part of ImGui
# -----------------------------------------------------------------------------
# imgui_color_text_edit.pyi: auto-generated bindings for ImGuiColorTextEdit,
# Based on the goossens rewrite: https://github.com/goossens/ImGuiColorTextEdit
# (originally created by BalazsJako, rewritten from scratch by Johan A. Goossens)
# In this bundle we use a fork: https://github.com/pthom/ImGuiColorTextEdit/tree/imgui_bundle
#
# Most of the code of this file is automatically generated (using https://pthom.github.io/litgen/),
# and is generally very close to the C++ version. Comments, docs are identical.
# Do not manually edit the autogenerated parts (look for "Autogenerated" comments)!
###############################################################################
"""
# Colorizing Text Editor and Text Diff for Dear ImGui

TextEdit is a syntax highlighting text editor for Dear ImGui and it was originally developed by Balázs Jákó. Unfortunately, he no longer has time to work on the project. In fact, the last update to his repository was in June 2019. As a result, over 200 forks exist by people who like his work but want to fix bugs and/or add new features. A fork by Santiago, also known as santaclose, was the most actively maintained version (over 220 commits ahead of the original version) when I was looking for a syntax highlighting text editor for Dear ImGui in late 2023. This repository was originally a fork of Santiago's version and I tried to enhance it.

In late December 2024, I decided that it was better for me to rewrite the code from the ground up while preserving the majority of the public APIs so it would be relatively simple for me (and others) to reuse my rewrite. One of my fundamental arguments for the rewrite was that the code had become hard to read and maintain (at least for me). I decided to create a more object-oriented internal architecture (see below) that made it clear who was responsible for what by using a layered approach. While rewriting the code, a number of new features were also added.

The rewrite and now the maintenance of this code is part of a larger project (ObjectTalk) and this repository is simply a snapshot of the relevant editor code to provide reuse. As part of this code is automatically generated, references to the master project are provided where required. You can find all text editor source code components here in the ObjectTalk repository.

To respect its origins, this repository will remain a fork (of a fork) although there is now little code in common.

"""
# ruff: noqa: F821, B008


# *** BREAKING CHANGES since v1.92.601 ***
# The underlying library was switched from the santaclose fork to the goossens
# rewrite. The API has changed significantly. Key changes:
#   - PaletteId enum → get_dark_palette() / get_light_palette()
#   - LanguageDefinitionId enum → Language class with static methods (e.g. Language.cpp())
#   - set_language_definition() → set_language()
#   - set_cursor_position() → set_cursor()
#   - get_selected_text() → get_cursor_text(cursor_index)
#   - render(title, border, size) → render(title, size, border), returns None
# See CHANGELOG.md for the full migration guide.


from __future__ import annotations
from typing import List, Any, Dict, Set, overload, Optional
import enum

from imgui_bundle.imgui import ImVec2Like, ImU32, ImVec2, ChildFlags, WindowFlags, ImDrawList
from typing import Callable

ImGuiChildFlags = ChildFlags
ImGuiWindowFlags = WindowFlags

String = str
Identifiers = Dict[
    str, Any
]  # Dict[str, Identifier] (but Identifier is defined later in the generated code)
Keywords = Set[str]
ErrorMarkers = Dict[int, str]
Breakpoints = Set[int]
Palette = List[int]
Char = int


# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  AUTOGENERATED CODE !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# <litgen_stub> // Autogenerated code below! Do not edit!
####################    <generated_from:TextEditor.h>    ####################
#	TextEditor - A syntax highlighting text editor for Dear ImGui.
#	Copyright (c) 2024-2026 Johan A. Goossens. All rights reserved.
#
#	This work is licensed under the terms of the MIT license.
#	For a copy, see <https://opensource.org/licenses/MIT>.




#
#	Include files
#




#
#	TextEditor
#

class TextEditor:
    # TextEditor();    /* original C++ signature */
    def __init__(self) -> None:
        """ constructor"""
        pass

    #
    # Below is the public API
    # Public member functions start with an uppercase character to be consistent with Dear ImGui
    #

    class DocPos:
        # DocPos() = default;    /* original C++ signature */
        @overload
        def __init__(self) -> None:
            """ represents the logical position of a glyph in a document expressed as a line number and glyph index (both zero-based)"""
            pass
        # DocPos(size_t line, size_t index) : line(line), index(index);    /* original C++ signature */
        @overload
        def __init__(self, line: int, index: int) -> None:
            pass

        # inline bool operator ==(const DocPos& rhs) const;    /* original C++ signature */
        def __eq__(self, rhs: object) -> bool:
            pass
        # inline bool operator !=(const DocPos& rhs) const;    /* original C++ signature */
        def __ne__(self, rhs: object) -> bool:
            pass
        # inline bool operator <(const DocPos& rhs) const;    /* original C++ signature */
        def __lt__(self, rhs: TextEditor.DocPos) -> bool:
            pass
        # inline bool operator >(const DocPos& rhs) const;    /* original C++ signature */
        def __gt__(self, rhs: TextEditor.DocPos) -> bool:
            pass
        # inline bool operator <=(const DocPos& rhs) const;    /* original C++ signature */
        def __le__(self, rhs: TextEditor.DocPos) -> bool:
            pass
        # inline bool operator >=(const DocPos& rhs) const;    /* original C++ signature */
        def __ge__(self, rhs: TextEditor.DocPos) -> bool:
            pass

        # inline DocPos operator -(const DocPos& rhs) const;    /* original C++ signature */
        def __sub__(self, rhs: TextEditor.DocPos) -> TextEditor.DocPos:
            pass
        # inline DocPos operator +(const DocPos& rhs) const;    /* original C++ signature */
        def __add__(self, rhs: TextEditor.DocPos) -> TextEditor.DocPos:
            pass

        # size_t line = 0;    /* original C++ signature */
        line: int = 0
        # size_t index = 0;    /* original C++ signature */
        index: int = 0

    class DocSelection:
        # DocSelection() = default;    /* original C++ signature */
        @overload
        def __init__(self) -> None:
            """ represents a range of glyphs from a starting position to an end position"""
            pass
        # DocSelection(DocPos start, DocPos end) : start(start), end(end);    /* original C++ signature */
        @overload
        def __init__(self, start: TextEditor.DocPos, end: TextEditor.DocPos) -> None:
            pass
        # DocPos start;    /* original C++ signature */
        start: TextEditor.DocPos
        # DocPos end;    /* original C++ signature */
        end: TextEditor.DocPos

    class VisPos:
        # VisPos() = default;    /* original C++ signature */
        @overload
        def __init__(self) -> None:
            """ represents the visual position of a glyph expressed as a visible row and column number (both zero-based)
             this is not necessarily the same as the document position
             tabs create a horizontal offset between index and column
             word-wrapping creates a vertical offset between line and row
            """
            pass
        # VisPos(size_t row, size_t column) : row(row), column(column);    /* original C++ signature */
        @overload
        def __init__(self, row: int, column: int) -> None:
            pass

        # inline bool operator ==(const VisPos& rhs) const;    /* original C++ signature */
        def __eq__(self, rhs: object) -> bool:
            pass
        # inline bool operator !=(const VisPos& rhs) const;    /* original C++ signature */
        def __ne__(self, rhs: object) -> bool:
            pass
        # inline bool operator <(const VisPos& rhs) const;    /* original C++ signature */
        def __lt__(self, rhs: TextEditor.VisPos) -> bool:
            pass
        # inline bool operator >(const VisPos& rhs) const;    /* original C++ signature */
        def __gt__(self, rhs: TextEditor.VisPos) -> bool:
            pass
        # inline bool operator <=(const VisPos& rhs) const;    /* original C++ signature */
        def __le__(self, rhs: TextEditor.VisPos) -> bool:
            pass
        # inline bool operator >=(const VisPos& rhs) const;    /* original C++ signature */
        def __ge__(self, rhs: TextEditor.VisPos) -> bool:
            pass

        # inline VisPos operator -(const VisPos& rhs) const;    /* original C++ signature */
        def __sub__(self, rhs: TextEditor.VisPos) -> TextEditor.VisPos:
            pass
        # inline VisPos operator +(const VisPos& rhs) const;    /* original C++ signature */
        def __add__(self, rhs: TextEditor.VisPos) -> TextEditor.VisPos:
            pass

        # size_t row = 0;    /* original C++ signature */
        row: int = 0
        # size_t column = 0;    /* original C++ signature */
        column: int = 0

    # access editor's configuration options
    # inline void SetTabSize(size_t value);    /* original C++ signature */
    def set_tab_size(self, value: int) -> None:
        pass
    # inline size_t GetTabSize() const;    /* original C++ signature */
    def get_tab_size(self) -> int:
        pass
    # inline void SetInsertSpacesOnTabs(bool value);    /* original C++ signature */
    def set_insert_spaces_on_tabs(self, value: bool) -> None:
        pass
    # inline bool IsInsertSpacesOnTabs() const;    /* original C++ signature */
    def is_insert_spaces_on_tabs(self) -> bool:
        pass
    # inline void SetLineSpacing(float value);    /* original C++ signature */
    def set_line_spacing(self, value: float) -> None:
        pass
    # inline float GetLineSpacing() const;    /* original C++ signature */
    def get_line_spacing(self) -> float:
        pass
    # inline void SetWordWrapEnabled(bool value);    /* original C++ signature */
    def set_word_wrap_enabled(self, value: bool) -> None:
        pass
    # inline bool IsWordWrapEnabled() const;    /* original C++ signature */
    def is_word_wrap_enabled(self) -> bool:
        pass
    # inline void SetReadOnlyEnabled(bool value);    /* original C++ signature */
    def set_read_only_enabled(self, value: bool) -> None:
        pass
    # inline bool IsReadOnlyEnabled() const;    /* original C++ signature */
    def is_read_only_enabled(self) -> bool:
        pass
    # inline void SetCaretsVisible(bool value);    /* original C++ signature */
    def set_carets_visible(self, value: bool) -> None:
        pass
    # inline bool IsCaretsVisible() const;    /* original C++ signature */
    def is_carets_visible(self) -> bool:
        pass
    # inline void SetAutoIndentEnabled(bool value);    /* original C++ signature */
    def set_auto_indent_enabled(self, value: bool) -> None:
        pass
    # inline bool IsAutoIndentEnabled() const;    /* original C++ signature */
    def is_auto_indent_enabled(self) -> bool:
        pass
    # inline void SetShowWhitespacesEnabled(bool value);    /* original C++ signature */
    def set_show_whitespaces_enabled(self, value: bool) -> None:
        pass
    # inline bool IsShowWhitespacesEnabled() const;    /* original C++ signature */
    def is_show_whitespaces_enabled(self) -> bool:
        pass
    # inline void SetShowSpacesEnabled(bool value);    /* original C++ signature */
    def set_show_spaces_enabled(self, value: bool) -> None:
        pass
    # inline bool IsShowSpacesEnabled() const;    /* original C++ signature */
    def is_show_spaces_enabled(self) -> bool:
        pass
    # inline void SetShowTabsEnabled(bool value);    /* original C++ signature */
    def set_show_tabs_enabled(self, value: bool) -> None:
        pass
    # inline bool IsShowTabsEnabled() const;    /* original C++ signature */
    def is_show_tabs_enabled(self) -> bool:
        pass
    # inline void SetShowLineNumbersEnabled(bool value);    /* original C++ signature */
    def set_show_line_numbers_enabled(self, value: bool) -> None:
        pass
    # inline bool IsShowLineNumbersEnabled() const;    /* original C++ signature */
    def is_show_line_numbers_enabled(self) -> bool:
        pass
    # inline void SetShowMiniMapEnabled(bool value);    /* original C++ signature */
    def set_show_mini_map_enabled(self, value: bool) -> None:
        pass
    # inline bool IsShowMiniMapEnabled() const;    /* original C++ signature */
    def is_show_mini_map_enabled(self) -> bool:
        pass
    # inline void SetMiniMapColumns(size_t value);    /* original C++ signature */
    def set_mini_map_columns(self, value: int) -> None:
        pass
    # inline size_t GetMiniMapColumns() const;    /* original C++ signature */
    def get_mini_map_columns(self) -> int:
        pass
    # inline void SetShowScrollbarMiniMapEnabled(bool value);    /* original C++ signature */
    def set_show_scrollbar_mini_map_enabled(self, value: bool) -> None:
        pass
    # inline bool IsShowScrollbarMiniMapEnabled() const;    /* original C++ signature */
    def is_show_scrollbar_mini_map_enabled(self) -> bool:
        pass
    # inline void SetShowPanScrollIndicatorEnabled(bool value);    /* original C++ signature */
    def set_show_pan_scroll_indicator_enabled(self, value: bool) -> None:
        pass
    # inline bool IsShowPanScrollIndicatorEnabled() const;    /* original C++ signature */
    def is_show_pan_scroll_indicator_enabled(self) -> bool:
        pass
    # inline void SetShowMatchingBrackets(bool value);    /* original C++ signature */
    def set_show_matching_brackets(self, value: bool) -> None:
        pass
    # inline bool IsShowingMatchingBrackets() const;    /* original C++ signature */
    def is_showing_matching_brackets(self) -> bool:
        pass
    # inline void SetCompletePairedGlyphs(bool value);    /* original C++ signature */
    def set_complete_paired_glyphs(self, value: bool) -> None:
        pass
    # inline bool IsCompletingPairedGlyphs() const;    /* original C++ signature */
    def is_completing_paired_glyphs(self) -> bool:
        pass
    # inline void SetLineFoldingEnabled(bool value);    /* original C++ signature */
    def set_line_folding_enabled(self, value: bool) -> None:
        pass
    # inline bool IsLineFoldingEnabled() const;    /* original C++ signature */
    def is_line_folding_enabled(self) -> bool:
        pass
    # inline void SetOverwriteEnabled(bool value);    /* original C++ signature */
    def set_overwrite_enabled(self, value: bool) -> None:
        pass
    # inline bool IsOverwriteEnabled() const;    /* original C++ signature */
    def is_overwrite_enabled(self) -> bool:
        pass
    # inline void SetMiddleMousePanMode();    /* original C++ signature */
    def set_middle_mouse_pan_mode(self) -> None:
        pass
    # inline void SetMiddleMouseScrollMode();    /* original C++ signature */
    def set_middle_mouse_scroll_mode(self) -> None:
        pass
    # inline bool IsMiddleMousePanMode() const;    /* original C++ signature */
    def is_middle_mouse_pan_mode(self) -> bool:
        pass
    # inline void SetLineNumberLeftMargin(size_t value);    /* original C++ signature */
    def set_line_number_left_margin(self, value: int) -> None:
        """ margins are expressed in glyphs"""
        pass
    # inline size_t GetLineNumberLeftMargin() const;    /* original C++ signature */
    def get_line_number_left_margin(self) -> int:
        pass
    # inline void SetDecorationLeftMargin(size_t value);    /* original C++ signature */
    def set_decoration_left_margin(self, value: int) -> None:
        pass
    # inline size_t GetDecorationLeftMargin() const;    /* original C++ signature */
    def get_decoration_left_margin(self) -> int:
        pass
    # inline void SetTextLeftMargin(size_t value);    /* original C++ signature */
    def set_text_left_margin(self, value: int) -> None:
        pass
    # inline size_t GetTextLeftMargin() const;    /* original C++ signature */
    def get_text_left_margin(self) -> int:
        pass

    # load new text into editor (see note below on cursor and scroll manipulation after setting new text)
    #
    # API calls to set/get text are available for all standard C++ UTF-8 and unicode string formats to support fast file en/de-coding
    # other API calls use UTF-8 encoded std::strings
    # Dear ImGui also uses UTF-8 encoding across the board for all internal string processing, text rendering, and widgets

    # load UTF-8 encoded string(s)
    # inline void SetText(const std::string_view& text);    /* original C++ signature */
    @overload
    def set_text(self, text: str) -> None:
        pass
    # inline void SetText(const std::vector<std::string_view>& lines);    /* original C++ signature */
    @overload
    def set_text(self, lines: List[str]) -> None:
        pass


    # load unicode encoded string(s)



    # inline std::string GetText() const;    /* original C++ signature */
    def get_text(self) -> str:
        """ get text from editor as UTF-8 encoded strings"""
        pass


    # get text from editor as unicode strings


    # get part of text from editor as UTF-8 encoded strings
    # inline std::string GetSectionText(DocPos start, DocPos end) const;    /* original C++ signature */
    @overload
    def get_section_text(self, start: TextEditor.DocPos, end: TextEditor.DocPos) -> str:
        pass
    # inline std::string GetSectionText(const DocSelection& selection) const;    /* original C++ signature */
    @overload
    def get_section_text(self, selection: TextEditor.DocSelection) -> str:
        pass
    # inline std::string GetCursorText(size_t cursor) const;    /* original C++ signature */
    def get_cursor_text(self, cursor: int) -> str:
        pass
    # inline std::string GetLineText(size_t line) const;    /* original C++ signature */
    def get_line_text(self, line: int) -> str:
        pass

    # replace text in editor (new text must be UTF-8 encoded)
    # inline void ReplaceSectionText(DocPos start, DocPos end, const std::string_view& text);    /* original C++ signature */
    @overload
    def replace_section_text(
        self,
        start: TextEditor.DocPos,
        end: TextEditor.DocPos,
        text: str
        ) -> None:
        pass
    # inline void ReplaceSectionText(const DocSelection& selection, const std::string_view& text);    /* original C++ signature */
    @overload
    def replace_section_text(self, selection: TextEditor.DocSelection, text: str) -> None:
        pass

    # inline void ClearText();    /* original C++ signature */
    def clear_text(self) -> None:
        """ clear the editor"""
        pass

    # get editor status
    # inline bool IsEmpty() const;    /* original C++ signature */
    def is_empty(self) -> bool:
        pass
    # inline size_t GetLineCount() const;    /* original C++ signature */
    def get_line_count(self) -> int:
        pass

    # inline bool Render(const char* title, const ImVec2& size=ImVec2(), ImGuiChildFlags childFlags=0, ImGuiWindowFlags windowFlags=ImGuiWindowFlags_NoMove | ImGuiWindowFlags_HorizontalScrollbar);    /* original C++ signature */
    def render(
        self,
        title: str,
        size: Optional[ImVec2Like] = None,
        child_flags: ImGuiChildFlags = 0,
        window_flags: Optional[ImGuiWindowFlags] = None
        ) -> bool:
        """ render the text editor in a Dear ImGui context
         note: if you overwrite windowFlags to for instance add ImGuiWindowFlags_NoSavedSettings
         ensure you keep the default as they are required for the editor
         - ImGuiWindowFlags_NoMove to ensure mouse drag event are passed to the editor
         - ImGuiWindowFlags_HorizontalScrollbar to ensure a horizontal scrollbar is rendered when required

        Python bindings defaults:
            If any of the params below is None, then its default value below will be used:
                * size: ImVec2()
                * windowFlags: ImGuiWindowFlags_NoMove | ImGuiWindowFlags_HorizontalScrollbar
        """
        pass

    # inline void SetFocus();    /* original C++ signature */
    def set_focus(self) -> None:
        """ programmatically set focus on the editor"""
        pass

    # clipboard actions
    # inline void Cut();    /* original C++ signature */
    def cut(self) -> None:
        pass
    # inline void Copy() const;    /* original C++ signature */
    def copy(self) -> None:
        pass
    # inline void Paste();    /* original C++ signature */
    def paste(self) -> None:
        pass
    # inline void Undo();    /* original C++ signature */
    def undo(self) -> None:
        pass
    # inline void Redo();    /* original C++ signature */
    def redo(self) -> None:
        pass
    # inline bool CanUndo() const;    /* original C++ signature */
    def can_undo(self) -> bool:
        pass
    # inline bool CanRedo() const;    /* original C++ signature */
    def can_redo(self) -> bool:
        pass
    # inline size_t GetUndoIndex() const;    /* original C++ signature */
    def get_undo_index(self) -> int:
        pass

    # manipulate cursors and selections (line numbers are zero-based)
    # inline void SelectAll();    /* original C++ signature */
    def select_all(self) -> None:
        pass
    # inline void SelectLine(size_t line);    /* original C++ signature */
    def select_line(self, line: int) -> None:
        pass
    # inline void SelectLines(size_t start, size_t end);    /* original C++ signature */
    def select_lines(self, start: int, end: int) -> None:
        pass
    # inline void SelectRegion(DocPos start, DocPos end);    /* original C++ signature */
    def select_region(self, start: TextEditor.DocPos, end: TextEditor.DocPos) -> None:
        pass
    # inline void SelectToBrackets(bool includeBrackets=true);    /* original C++ signature */
    def select_to_brackets(self, include_brackets: bool = True) -> None:
        pass
    # inline void GrowSelections();    /* original C++ signature */
    def grow_selections(self) -> None:
        pass
    # inline void ShrinkSelections();    /* original C++ signature */
    def shrink_selections(self) -> None:
        pass
    # inline void AddNextOccurrence(bool wholeWord=false);    /* original C++ signature */
    def add_next_occurrence(self, whole_word: bool = False) -> None:
        pass
    # inline void SelectAllOccurrences(bool wholeWord=false);    /* original C++ signature */
    def select_all_occurrences(self, whole_word: bool = False) -> None:
        pass
    # inline bool AnyCursorHasSelection() const;    /* original C++ signature */
    def any_cursor_has_selection(self) -> bool:
        pass
    # inline bool AllCursorsHaveSelection() const;    /* original C++ signature */
    def all_cursors_have_selection(self) -> bool:
        pass
    # inline bool CursorHasSelection(size_t cursor) const;    /* original C++ signature */
    def cursor_has_selection(self, cursor: int) -> bool:
        pass
    # inline bool MainCursorHasSelection() const;    /* original C++ signature */
    def main_cursor_has_selection(self) -> bool:
        pass
    # inline bool CurrentCursorHasSelection() const;    /* original C++ signature */
    def current_cursor_has_selection(self) -> bool:
        pass
    # inline void ClearCursors();    /* original C++ signature */
    def clear_cursors(self) -> None:
        pass

    # get cursor positions (the meaning of main and current is explained in README.md)
    # inline size_t GetNumberOfCursors() const;    /* original C++ signature */
    def get_number_of_cursors(self) -> int:
        pass
    # inline DocPos GetCursorPosition(size_t cursor) const;    /* original C++ signature */
    def get_cursor_position(self, cursor: int) -> TextEditor.DocPos:
        pass
    # inline DocPos GetMainCursorPosition() const;    /* original C++ signature */
    def get_main_cursor_position(self) -> TextEditor.DocPos:
        pass
    # inline DocPos GetCurrentCursorPosition() const;    /* original C++ signature */
    def get_current_cursor_position(self) -> TextEditor.DocPos:
        pass
    # inline DocSelection GetCursorSelection(size_t cursor) const;    /* original C++ signature */
    def get_cursor_selection(self, cursor: int) -> TextEditor.DocSelection:
        pass
    # inline DocSelection GetMainCursorSelection() const;    /* original C++ signature */
    def get_main_cursor_selection(self) -> TextEditor.DocSelection:
        pass
    # inline DocSelection GetCurrentCursorSelection() const;    /* original C++ signature */
    def get_current_cursor_selection(self) -> TextEditor.DocSelection:
        pass

    # get information at mouse position (e.g. from ImGui::GetMousePos())
    # inline bool IsMousePosOverGlyph(const ImVec2& mousePos) const;    /* original C++ signature */
    def is_mouse_pos_over_glyph(self, mouse_pos: ImVec2Like) -> bool:
        pass
    # inline bool IsMousePosOverTextArea(const ImVec2& mousePos) const;    /* original C++ signature */
    def is_mouse_pos_over_text_area(self, mouse_pos: ImVec2Like) -> bool:
        pass
    # inline DocPos GetDocPosAtMousePos(const ImVec2& mousePos) const;    /* original C++ signature */
    def get_doc_pos_at_mouse_pos(self, mouse_pos: ImVec2Like) -> TextEditor.DocPos:
        pass
    # inline std::string GetWordAtMousePos(const ImVec2& mousePos) const;    /* original C++ signature */
    def get_word_at_mouse_pos(self, mouse_pos: ImVec2Like) -> str:
        pass

    class Scroll(enum.IntEnum):
        """ scrolling support"""
        # alignTop,    /* original C++ signature */
        align_top = enum.auto()                   # (= 0)
        # alignMiddle,    /* original C++ signature */
        align_middle = enum.auto()                # (= 1)
        # alignBottom    /* original C++ signature */
        # 	}
        align_bottom = enum.auto()                # (= 2)

    # inline void ScrollToLine(size_t line, Scroll alignment=Scroll::alignMiddle);    /* original C++ signature */
    def scroll_to_line(
        self,
        line: int,
        alignment: TextEditor.Scroll = TextEditor.Scroll.align_middle
        ) -> None:
        pass
    # inline size_t GetFirstVisibleRow() const;    /* original C++ signature */
    def get_first_visible_row(self) -> int:
        pass
    # inline size_t GetLastVisibleRow() const;    /* original C++ signature */
    def get_last_visible_row(self) -> int:
        pass
    # inline size_t GetFirstVisibleColumn() const;    /* original C++ signature */
    def get_first_visible_column(self) -> int:
        pass
    # inline size_t GetLastVisibleColumn() const;    /* original C++ signature */
    def get_last_visible_column(self) -> int:
        pass

    # inline void SetCursor(DocPos pos);    /* original C++ signature */
    def set_cursor(self, pos: TextEditor.DocPos) -> None:
        """ specify a new cursor position and scroll to it (if required)
         if the new position is currently in a folded region, it will be automatically unfolded
        """
        pass

    # note on setting scrolling and cursor position
    #
    # calling SetCursor or ScrollToLine has no effect until the next call to Render
    # this is because we can only do layout calculations when we are in a Dear ImGui drawing context
    # as a result, SetCursor or ScrollToLine just mark the request and let Render execute it
    #
    # the order of the calls is therefore important as they can interfere with each other
    # so if you call SetText, SetCursor and/or ScrollToLine before Render, the order should be:
    #
    # * call SetText first as it resets the entire editor state including cursors and scrolling
    # * then call SetCursor as it sets the cursor and requests that we make the cursor visible (i.e. scroll to it)
    # * then call ScrollToLine to mark the exact scroll location (it cancels the possible SetCursor scroll request)
    # * call Render to properly update the entire state
    #
    # this works while opening the editor for the first time as well as later

    # get glyph size in pixels
    # inline float GetLineHeight() const;    /* original C++ signature */
    def get_line_height(self) -> float:
        pass
    # inline float GetGlyphWidth() const;    /* original C++ signature */
    def get_glyph_width(self) -> float:
        pass

    # coordinate transformation
    # inline VisPos DocPos2VisPos(DocPos pos) const;    /* original C++ signature */
    def doc_pos2_vis_pos(self, pos: TextEditor.DocPos) -> TextEditor.VisPos:
        pass
    # inline DocPos VisPos2DocPos(VisPos pos) const;    /* original C++ signature */
    def vis_pos2_doc_pos(self, pos: TextEditor.VisPos) -> TextEditor.DocPos:
        pass

    # inline bool IsDocPosVisible(DocPos pos) const;    /* original C++ signature */
    def is_doc_pos_visible(self, pos: TextEditor.DocPos) -> bool:
        """ see if a specified document location is visible (not folded and currently on screen)"""
        pass

    # inline bool IsVisPosOverGlyph(VisPos pos) const;    /* original C++ signature */
    def is_vis_pos_over_glyph(self, pos: TextEditor.VisPos) -> bool:
        """ see if a visual position covers a glyph"""
        pass

    # find start or end of word from provided position
    # inline DocPos FindWordStart(DocPos pos, bool wholeWord=false) const;    /* original C++ signature */
    def find_word_start(
        self,
        pos: TextEditor.DocPos,
        whole_word: bool = False
        ) -> TextEditor.DocPos:
        pass
    # inline DocPos FindWordEnd(DocPos pos, bool wholeWord=false) const;    /* original C++ signature */
    def find_word_end(
        self,
        pos: TextEditor.DocPos,
        whole_word: bool = False
        ) -> TextEditor.DocPos:
        pass

    # find/replace support (strings must be UTF-8 encoded)
    # inline void SelectFirstOccurrenceOf(const std::string_view& text, bool caseSensitive=true, bool wholeWord=false);    /* original C++ signature */
    def select_first_occurrence_of(
        self,
        text: str,
        case_sensitive: bool = True,
        whole_word: bool = False
        ) -> None:
        pass
    # inline void SelectNextOccurrenceOf(const std::string_view& text, bool caseSensitive=true, bool wholeWord=false);    /* original C++ signature */
    def select_next_occurrence_of(
        self,
        text: str,
        case_sensitive: bool = True,
        whole_word: bool = False
        ) -> None:
        pass
    # inline void SelectAllOccurrencesOf(const std::string_view& text, bool caseSensitive=true, bool wholeWord=false);    /* original C++ signature */
    def select_all_occurrences_of(
        self,
        text: str,
        case_sensitive: bool = True,
        whole_word: bool = False
        ) -> None:
        pass
    # inline void ReplaceTextInCurrentCursor(const std::string_view& text);    /* original C++ signature */
    def replace_text_in_current_cursor(self, text: str) -> None:
        pass
    # inline void ReplaceTextInAllCursors(const std::string_view& text);    /* original C++ signature */
    def replace_text_in_all_cursors(self, text: str) -> None:
        pass

    # inline void OpenFindReplaceWindow();    /* original C++ signature */
    def open_find_replace_window(self) -> None:
        pass
    # inline void CloseFindReplaceWindow();    /* original C++ signature */
    def close_find_replace_window(self) -> None:
        pass
    # inline bool HasFindString() const;    /* original C++ signature */
    def has_find_string(self) -> bool:
        pass
    # inline void FindNext();    /* original C++ signature */
    def find_next(self) -> None:
        pass
    # inline void FindAll();    /* original C++ signature */
    def find_all(self) -> None:
        pass

    # internationalize find window labels (strings must be UTF-8 encoded)
    # inline void SetFindButtonLabel(const std::string_view& label);    /* original C++ signature */
    def set_find_button_label(self, label: str) -> None:
        pass
    # inline void SetFindAllButtonLabel(const std::string_view& label);    /* original C++ signature */
    def set_find_all_button_label(self, label: str) -> None:
        pass
    # inline void SetReplaceButtonLabel(const std::string_view& label);    /* original C++ signature */
    def set_replace_button_label(self, label: str) -> None:
        pass
    # inline void SetReplaceAllButtonLabel(const std::string_view& label);    /* original C++ signature */
    def set_replace_all_button_label(self, label: str) -> None:
        pass

    # access markers (line numbers are zero-based)
    # markers are attached to lines and are not effected by inserts or deletes before that line
    # if a line with a marker is deleted, undo doesn't restore it
    # tooltips must be UTF-8 encoded
    # inline void AddMarker(size_t line, ImU32 lineNumberColor, ImU32 textColor, const std::string_view& lineNumberTooltip, const std::string_view& textTooltip);    /* original C++ signature */
    def add_marker(
        self,
        line: int,
        line_number_color: ImU32,
        text_color: ImU32,
        line_number_tooltip: str,
        text_tooltip: str
        ) -> None:
        pass
    # inline void ClearMarkers();    /* original C++ signature */
    def clear_markers(self) -> None:
        pass
    # inline bool HasMarkers() const;    /* original C++ signature */
    def has_markers(self) -> bool:
        pass

    # access squiggly underlines
    # squiggles are attached to glyphs and are not effected  by inserts or deletes before that glyph
    # if a glyph with a squiggle is deleted, undo doesn't restore it
    # tooltips must be UTF-8 encoded
    # inline void AddSquiggle(DocPos start, DocPos end, size_t type, ImU32 color, const std::string_view& tooltip = std::string_view());    /* original C++ signature */
    def add_squiggle(
        self,
        start: TextEditor.DocPos,
        end: TextEditor.DocPos,
        type: int,
        color: ImU32,
        tooltip: str = str()
        ) -> None:
        pass
    # inline void ClearSquiggles(DocPos start, DocPos end);    /* original C++ signature */
    @overload
    def clear_squiggles(self, start: TextEditor.DocPos, end: TextEditor.DocPos) -> None:
        pass
    # inline void ClearSquiggles(size_t type);    /* original C++ signature */
    @overload
    def clear_squiggles(self, type: int) -> None:
        pass
    # inline void ClearSquiggles();    /* original C++ signature */
    @overload
    def clear_squiggles(self) -> None:
        pass
    # inline bool HasSquiggles() const;    /* original C++ signature */
    def has_squiggles(self) -> bool:
        pass

    # inline void SetChangeCallback(std::function<void()> callback, int delay=0);    /* original C++ signature */
    def set_change_callback(self, callback: Callable[[], None], delay: int = 0) -> None:
        """ specify a change callback (called when changes are made (including undo/redo))
         the delay parameter specifies a time in miliseconds that the editor will wait for before calling
         which helps in case you don't need to track every keystroke
        """
        pass

    # inline void ClearChangeCallback();    /* original C++ signature */
    def clear_change_callback(self) -> None:
        pass
    # inline bool HasChangeCallback() const;    /* original C++ signature */
    def has_change_callback(self) -> bool:
        pass

    class Change:
        """ detailed change report passed to callback below
         this callback is different from the one above as it reports every change (not just a summary) and is very detailed
         the insert flag states whether the change was an insert (True) or a delete (False)
         in case of an overwrite, there will be two actions (first a delete and then an insert)
         the start parameters refer to the insert point or the start of the delete
         the end parameters refer to the end of the inserted text or the end of the deleted text
         the text parameter contains the inserted or deleted text (UTF-8 encoded)
         line and index values are zero-based
        """
        # bool insert;    /* original C++ signature */
        insert: bool
        # DocPos start;    /* original C++ signature */
        start: TextEditor.DocPos
        # DocPos end;    /* original C++ signature */
        end: TextEditor.DocPos
        # std::string text;    /* original C++ signature */
        text: str
        # Change(bool insert = bool(), DocPos start = DocPos(), DocPos end = DocPos(), std::string text = std::string());    /* original C++ signature */
        def __init__(
            self,
            insert: bool = bool(),
            start: Optional[TextEditor.DocPos] = None,
            end: Optional[TextEditor.DocPos] = None,
            text: str = ""
            ) -> None:
            """Auto-generated default constructor with named params

            Python bindings defaults:
                If any of the params below is None, then its default value below will be used:
                    * start: TextEditor.DocPos()
                    * end: TextEditor.DocPos()
            """
            pass

    # specify a transaction callback (live document changes in great detail)
    # it provides a list of changes made to the document in a single transaction (in the right order)
    # be carefull with this callback as it gets very verbose (called on every keystroke, delete, cut, paste, undo and redo)
    # inline void SetTransactionCallback(std::function<void(const std::vector<Change>&)> callback);    /* original C++ signature */
    def set_transaction_callback(
        self,
        callback: Callable[[List[TextEditor.Change]], None]
        ) -> None:
        pass
    # inline void ClearTransactionCallback();    /* original C++ signature */
    def clear_transaction_callback(self) -> None:
        pass
    # inline bool HasTransactionCallback() const;    /* original C++ signature */
    def has_transaction_callback(self) -> bool:
        pass

    # line-based callbacks (line numbers are zero-based)
    # insertor callback is called for each line inserted and the result is used as the new line specific user data
    # deletor callback is called for each line deleted (line specific user data is passed to callback)


    # line-based user data (line numbers are zero-based)
    # allowing integrators to associate external data with select lines
    # user data is an opaque None* that must be managed externally
    # user data is also passed to the decorator and popup callbacks (see below)
    # user data is attached to a line and insertions/deletions don't effect this
    # if a line with user data is removed, it won't come back on a redo
    # the deletor callback (if specified) is called when a line is deleted (see above)

    class Decorator:
        """ line-based decoration"""
        # size_t line;    /* original C++ signature */
        line: int                                 # zero-based
        # float width;    /* original C++ signature */
        width: float
        # float height;    /* original C++ signature */
        height: float
        # ImVec2 glyphSize;    /* original C++ signature */
        glyph_size: ImVec2
        # Decorator(size_t line = size_t(), float width = float(), float height = float(), ImVec2 glyphSize = ImVec2());    /* original C++ signature */
        def __init__(
            self,
            line: int = int(),
            width: float = float(),
            height: float = float(),
            glyph_size: Optional[ImVec2Like] = None
            ) -> None:
            """Auto-generated default constructor with named params

            Python bindings defaults:
                If glyphSize is None, then its default value will be: ImVec2()
            """
            pass

    # inline void SetLineDecorator(size_t width, std::function<void(Decorator& decorator)> callback);    /* original C++ signature */
    def set_line_decorator(
        self,
        width: int,
        callback: Callable[[TextEditor.Decorator], None]
        ) -> None:
        """ setup a line decorator (width is number of glyphs)"""
        pass

    # inline void ClearLineDecorator();    /* original C++ signature */
    def clear_line_decorator(self) -> None:
        pass
    # inline bool HasLineDecorator() const;    /* original C++ signature */
    def has_line_decorator(self) -> bool:
        pass

    class CustomCaret:
        """ custom text cursor (caret) rendering"""
        # ImDrawList* drawList;    /* original C++ signature */
        # draw list to submit rendering commands to
        draw_list: ImDrawList

        # ImVec2 glyphPos;    /* original C++ signature */
        # top left corner of glyph where cursor is (in screen coordinates)
        # can be used directly to submit drawing commands
        glyph_pos: ImVec2

        # ImVec2 glyphSize;    /* original C++ signature */
        # visible size of glyph
        glyph_size: ImVec2

        # bool caretVisible;    /* original C++ signature */
        # flag indicating if cursor is visible (based on configuration and standard blinking algorithm)
        # this can be ignored if the custom caret has its own animation algorithm
        caret_visible: bool

        # ImU32 caretColor;    /* original C++ signature */
        # color of cursor caret as per the current palette
        # this can also be ignored if custom caret has its own palette or animation
        caret_color: ImU32

        # size_t cursorIndex;    /* original C++ signature */
        # index of the cursor being rendered (in case additional cursor information is required)
        cursor_index: int
        # CustomCaret(ImVec2 glyphPos = ImVec2(), ImVec2 glyphSize = ImVec2(), bool caretVisible = bool(), ImU32 caretColor = ImU32(), size_t cursorIndex = size_t());    /* original C++ signature */
        def __init__(
            self,
            glyph_pos: Optional[ImVec2Like] = None,
            glyph_size: Optional[ImVec2Like] = None,
            caret_visible: bool = bool(),
            caret_color: Optional[ImU32] = None,
            cursor_index: int = int()
            ) -> None:
            """Auto-generated default constructor with named params

            Python bindings defaults:
                If any of the params below is None, then its default value below will be used:
                    * glyphPos: ImVec2()
                    * glyphSize: ImVec2()
                    * caretColor: ImU32()
            """
            pass

    # inline void SetCustomCaretRenderer(std::function<void(const CustomCaret& data)> callback);    /* original C++ signature */
    def set_custom_caret_renderer(
        self,
        callback: Callable[[TextEditor.CustomCaret], None]
        ) -> None:
        pass
    # inline void ClearCustomCaretRenderer();    /* original C++ signature */
    def clear_custom_caret_renderer(self) -> None:
        pass
    # inline bool HasCustomCaretRenderer() const;    /* original C++ signature */
    def has_custom_caret_renderer(self) -> bool:
        pass

    class CustomLineNumber:
        """ custom line number renderer"""
        # ImDrawList* drawList;    /* original C++ signature */
        # draw list to submit rendering commands to
        draw_list: ImDrawList

        # ImVec2 pos;    /* original C++ signature */
        # top left corner of line number box
        # can be used directly to submit drawing commands
        pos: ImVec2

        # ImVec2 size;    /* original C++ signature */
        # visible size of line number box in pixels
        size: ImVec2

        # size_t digits;    /* original C++ signature */
        # width of line number box in glyphs (this is variable)
        # the editor calculates the number of digits required for the highest line number
        digits: int

        # size_t lineNumber;    /* original C++ signature */
        # line number to be rendered (zero-based)
        line_number: int

        # size_t cursorLineNumber;    /* original C++ signature */
        # line number for current cursor (zero-based)
        cursor_line_number: int

        # ImU32 color;    /* original C++ signature */
        # line number color from current palette
        # this can be ignored if custom renderer has its own palette or animation
        color: ImU32
        # CustomLineNumber(ImVec2 pos = ImVec2(), ImVec2 size = ImVec2(), size_t digits = size_t(), size_t lineNumber = size_t(), size_t cursorLineNumber = size_t(), ImU32 color = ImU32());    /* original C++ signature */
        def __init__(
            self,
            pos: Optional[ImVec2Like] = None,
            size: Optional[ImVec2Like] = None,
            digits: int = int(),
            line_number: int = int(),
            cursor_line_number: int = int(),
            color: Optional[ImU32] = None
            ) -> None:
            """Auto-generated default constructor with named params

            Python bindings defaults:
                If any of the params below is None, then its default value below will be used:
                    * pos: ImVec2()
                    * size: ImVec2()
                    * color: ImU32()
            """
            pass

    # inline void SetCustomLineNumberRenderer(std::function<void(const CustomLineNumber& data)> callback);    /* original C++ signature */
    def set_custom_line_number_renderer(
        self,
        callback: Callable[[TextEditor.CustomLineNumber], None]
        ) -> None:
        pass
    # inline void ClearCustomLineNumberRenderer();    /* original C++ signature */
    def clear_custom_line_number_renderer(self) -> None:
        pass
    # inline bool HasCustomLineNumberRenderer() const;    /* original C++ signature */
    def has_custom_line_number_renderer(self) -> bool:
        pass

    class PopupData:
        """ setup right click or hover callbacks
         the editor sets up a popup menu in the right location
         the callback has to populate it
         context callbacks activate on a right click
         hover callbacks are just based on position (no mouse buttons required)
        """
        # DocPos pos;    /* original C++ signature */
        pos: TextEditor.DocPos
        # PopupData(DocPos pos = DocPos());    /* original C++ signature */
        def __init__(self, pos: Optional[TextEditor.DocPos] = None) -> None:
            """Auto-generated default constructor with named params

            Python bindings defaults:
                If pos is None, then its default value will be: TextEditor.DocPos()
            """
            pass

    # inline void SetLineNumberContextMenuCallback(std::function<void(PopupData& data)> callback);    /* original C++ signature */
    def set_line_number_context_menu_callback(
        self,
        callback: Callable[[TextEditor.PopupData], None]
        ) -> None:
        pass
    # inline void ClearLineNumberContextMenuCallback();    /* original C++ signature */
    def clear_line_number_context_menu_callback(self) -> None:
        pass
    # inline bool HasLineNumberContextMenuCallback() const;    /* original C++ signature */
    def has_line_number_context_menu_callback(self) -> bool:
        pass

    # inline void SetTextContextMenuCallback(std::function<void(PopupData& data)> callback);    /* original C++ signature */
    def set_text_context_menu_callback(
        self,
        callback: Callable[[TextEditor.PopupData], None]
        ) -> None:
        pass
    # inline void ClearTextContextMenuCallback();    /* original C++ signature */
    def clear_text_context_menu_callback(self) -> None:
        pass
    # inline bool HasTextContextMenuCallback() const;    /* original C++ signature */
    def has_text_context_menu_callback(self) -> bool:
        pass

    # inline void SetTextHoverCallback(std::function<void(PopupData& data)> callback);    /* original C++ signature */
    def set_text_hover_callback(
        self,
        callback: Callable[[TextEditor.PopupData], None]
        ) -> None:
        pass
    # inline void ClearTextHoverCallback();    /* original C++ signature */
    def clear_text_hover_callback(self) -> None:
        pass
    # inline bool HasTextHoverCallback() const;    /* original C++ signature */
    def has_text_hover_callback(self) -> bool:
        pass

    # line folding support (only works when line folding is activated)
    # inline void FoldAroundLine(size_t line);    /* original C++ signature */
    def fold_around_line(self, line: int) -> None:
        pass
    # inline void UnfoldAroundLine(size_t line);    /* original C++ signature */
    def unfold_around_line(self, line: int) -> None:
        pass
    # inline void ToggleAtLine(size_t line);    /* original C++ signature */
    def toggle_at_line(self, line: int) -> None:
        pass
    # inline void UnfoldAll();    /* original C++ signature */
    def unfold_all(self) -> None:
        pass

    # inline bool IsLineFoldable(size_t line) const;    /* original C++ signature */
    def is_line_foldable(self, line: int) -> bool:
        pass
    # inline bool IsLineFolded(size_t line) const;    /* original C++ signature */
    def is_line_folded(self, line: int) -> bool:
        pass
    # inline bool IsLineVisible(size_t line) const;    /* original C++ signature */
    def is_line_visible(self, line: int) -> bool:
        pass
    # inline bool IsLineHidden(size_t line) const;    /* original C++ signature */
    def is_line_hidden(self, line: int) -> bool:
        pass

    # useful functions to work on selections
    # NOTE: functions provided to FilterSelections or FilterLines should accept and return UTF-8 encoded strings
    # inline void IndentLines();    /* original C++ signature */
    def indent_lines(self) -> None:
        pass
    # inline void DeindentLines();    /* original C++ signature */
    def deindent_lines(self) -> None:
        pass
    # inline void MoveUpLines();    /* original C++ signature */
    def move_up_lines(self) -> None:
        pass
    # inline void MoveDownLines();    /* original C++ signature */
    def move_down_lines(self) -> None:
        pass
    # inline void ToggleComments();    /* original C++ signature */
    def toggle_comments(self) -> None:
        pass
    # inline void FilterSelections(std::function<std::string(std::string_view)> filter);    /* original C++ signature */
    def filter_selections(self, filter: Callable[[str], str]) -> None:
        pass
    # inline void SelectionToLowerCase();    /* original C++ signature */
    def selection_to_lower_case(self) -> None:
        pass
    # inline void SelectionToUpperCase();    /* original C++ signature */
    def selection_to_upper_case(self) -> None:
        pass

    # useful functions to work on entire text
    # inline void StripTrailingWhitespaces();    /* original C++ signature */
    def strip_trailing_whitespaces(self) -> None:
        pass
    # inline void FilterLines(std::function<std::string(std::string_view)> filter);    /* original C++ signature */
    def filter_lines(self, filter: Callable[[str], str]) -> None:
        pass
    # inline void TabsToSpaces();    /* original C++ signature */
    def tabs_to_spaces(self) -> None:
        pass
    # inline void SpacesToTabs();    /* original C++ signature */
    def spaces_to_tabs(self) -> None:
        pass

    class Color(enum.IntEnum):
        """ color palette support"""
        # text,    /* original C++ signature */
        text = enum.auto()                        # (= 0)
        # keyword,    /* original C++ signature */
        keyword = enum.auto()                     # (= 1)
        # declaration,    /* original C++ signature */
        declaration = enum.auto()                 # (= 2)
        # number,    /* original C++ signature */
        number = enum.auto()                      # (= 3)
        # string,    /* original C++ signature */
        string = enum.auto()                      # (= 4)
        # punctuation,    /* original C++ signature */
        punctuation = enum.auto()                 # (= 5)
        # preprocessor,    /* original C++ signature */
        preprocessor = enum.auto()                # (= 6)
        # identifier,    /* original C++ signature */
        identifier = enum.auto()                  # (= 7)
        # knownIdentifier,    /* original C++ signature */
        known_identifier = enum.auto()            # (= 8)
        # comment,    /* original C++ signature */
        comment = enum.auto()                     # (= 9)
        # background,    /* original C++ signature */
        background = enum.auto()                  # (= 10)
        # cursor,    /* original C++ signature */
        cursor = enum.auto()                      # (= 11)
        # selection,    /* original C++ signature */
        selection = enum.auto()                   # (= 12)
        # whitespace,    /* original C++ signature */
        whitespace = enum.auto()                  # (= 13)
        # matchingBracketBackground,    /* original C++ signature */
        matching_bracket_background = enum.auto() # (= 14)
        # matchingBracketActive,    /* original C++ signature */
        matching_bracket_active = enum.auto()     # (= 15)
        # matchingBracketLevel1,    /* original C++ signature */
        matching_bracket_level1 = enum.auto()     # (= 16)
        # matchingBracketLevel2,    /* original C++ signature */
        matching_bracket_level2 = enum.auto()     # (= 17)
        # matchingBracketLevel3,    /* original C++ signature */
        matching_bracket_level3 = enum.auto()     # (= 18)
        # matchingBracketError,    /* original C++ signature */
        matching_bracket_error = enum.auto()      # (= 19)
        # lineNumber,    /* original C++ signature */
        line_number = enum.auto()                 # (= 20)
        # currentLineNumber,    /* original C++ signature */
        current_line_number = enum.auto()         # (= 21)

    class Palette:
        # inline ImU32 get(Color color) const;    /* original C++ signature */
        def get(self, color: TextEditor.Color) -> ImU32:
            pass
        # Palette();    /* original C++ signature */
        def __init__(self) -> None:
            """Auto-generated default constructor"""
            pass

    # inline void SetPalette(const Palette& newPalette);    /* original C++ signature */
    def set_palette(self, new_palette: TextEditor.Palette) -> None:
        pass
    # inline const Palette& GetPalette() const;    /* original C++ signature */
    def get_palette(self) -> TextEditor.Palette:
        pass
    # static inline void SetDefaultPalette(const Palette& aValue);    /* original C++ signature */
    @staticmethod
    def set_default_palette(a_value: TextEditor.Palette) -> None:
        pass
    # static inline Palette& GetDefaultPalette();    /* original C++ signature */
    @staticmethod
    def get_default_palette() -> TextEditor.Palette:
        pass

    # static const Palette& GetDarkPalette();    /* original C++ signature */
    @staticmethod
    def get_dark_palette() -> TextEditor.Palette:
        pass
    # static const Palette& GetLightPalette();    /* original C++ signature */
    @staticmethod
    def get_light_palette() -> TextEditor.Palette:
        pass




    class Language:
        """ language support"""
        # predefined language definitions
        # static const Language* C();    /* original C++ signature */
        @staticmethod
        def c() -> TextEditor.Language:
            pass
        # static const Language* Cpp();    /* original C++ signature */
        @staticmethod
        def cpp() -> TextEditor.Language:
            pass
        # static const Language* Cs();    /* original C++ signature */
        @staticmethod
        def cs() -> TextEditor.Language:
            pass
        # static const Language* AngelScript();    /* original C++ signature */
        @staticmethod
        def angel_script() -> TextEditor.Language:
            pass
        # static const Language* Lua();    /* original C++ signature */
        @staticmethod
        def lua() -> TextEditor.Language:
            pass
        # static const Language* Python();    /* original C++ signature */
        @staticmethod
        def python() -> TextEditor.Language:
            pass
        # static const Language* Glsl();    /* original C++ signature */
        @staticmethod
        def glsl() -> TextEditor.Language:
            pass
        # static const Language* Hlsl();    /* original C++ signature */
        @staticmethod
        def hlsl() -> TextEditor.Language:
            pass
        # static const Language* Json();    /* original C++ signature */
        @staticmethod
        def json() -> TextEditor.Language:
            pass
        # static const Language* Markdown();    /* original C++ signature */
        @staticmethod
        def markdown() -> TextEditor.Language:
            pass
        # static const Language* Sql();    /* original C++ signature */
        @staticmethod
        def sql() -> TextEditor.Language:
            pass
        # Language();    /* original C++ signature */
        def __init__(self) -> None:
            """Auto-generated default constructor"""
            pass

    # void SetLanguage(const Language* language);    /* original C++ signature */
    def set_language(self, language: TextEditor.Language) -> None:
        pass
    # inline const Language* GetLanguage() const;    /* original C++ signature */
    def get_language(self) -> TextEditor.Language:
        pass
    # inline bool HasLanguage() const;    /* original C++ signature */
    def has_language(self) -> bool:
        pass
    # inline std::string GetLanguageName() const;    /* original C++ signature */
    def get_language_name(self) -> str:
        pass
    # inline void SetLanguageChangeCallback(std::function<void()> callback);    /* original C++ signature */
    def set_language_change_callback(self, callback: Callable[[], None]) -> None:
        pass

    # inline void IterateIdentifiers(std::function<void(const std::string& identifier)> callback) const;    /* original C++ signature */
    def iterate_identifiers(self, callback: Callable[[str], None]) -> None:
        """ iterate through identifiers detected by the colorizer (based on current language)"""
        pass






    class LineBreakConfig:
        """ configuration for line break algorithm used when word wrap is active"""
        # bool useUnicodeAnnex14 = false;    /* original C++ signature */
        # wrap mode (False = simple mode, True = unicode line break mode)
        use_unicode_annex14: bool = False

        # simple mode options (strings of UTF-8 encoded glyphs)
        # std::string breakAfter = " \t{[(";    /* original C++ signature */
        break_after: str = " \t{[("
        # std::string breakBefore = ".";    /* original C++ signature */
        break_before: str = "."

        # unicode line breaking options
        # based on the unicode standard annex     #14 which identifies break
        # opportunities expressed as rules which can be (de)activated below
        # see https://www.unicode.org/reports/tr14 for details
        # bool lb2 = true;    /* original C++ signature */
        lb2: bool = True
        # bool lb3 = true;    /* original C++ signature */
        lb3: bool = True
        # bool lb4 = true;    /* original C++ signature */
        lb4: bool = True
        # bool lb5 = true;    /* original C++ signature */
        lb5: bool = True
        # bool lb6 = true;    /* original C++ signature */
        lb6: bool = True
        # bool lb7 = true;    /* original C++ signature */
        lb7: bool = True
        # bool lb8 = true;    /* original C++ signature */
        lb8: bool = True
        # bool lb8a = true;    /* original C++ signature */
        lb8a: bool = True
        # bool lb9 = true;    /* original C++ signature */
        lb9: bool = True
        # bool lb10 = true;    /* original C++ signature */
        lb10: bool = True
        # bool lb11 = true;    /* original C++ signature */
        lb11: bool = True
        # bool lb12 = true;    /* original C++ signature */
        lb12: bool = True
        # bool lb12a = true;    /* original C++ signature */
        lb12a: bool = True
        # bool lb13 = true;    /* original C++ signature */
        lb13: bool = True
        # bool lb14 = true;    /* original C++ signature */
        lb14: bool = True
        # bool lb15a = true;    /* original C++ signature */
        lb15a: bool = True
        # bool lb15b = true;    /* original C++ signature */
        lb15b: bool = True
        # bool lb15c = true;    /* original C++ signature */
        lb15c: bool = True
        # bool lb15d = true;    /* original C++ signature */
        lb15d: bool = True
        # bool lb16 = true;    /* original C++ signature */
        lb16: bool = True
        # bool lb17 = true;    /* original C++ signature */
        lb17: bool = True
        # bool lb18 = true;    /* original C++ signature */
        lb18: bool = True
        # bool lb19 = true;    /* original C++ signature */
        lb19: bool = True
        # bool lb19a = true;    /* original C++ signature */
        lb19a: bool = True
        # bool lb20 = true;    /* original C++ signature */
        lb20: bool = True
        # bool lb20a = true;    /* original C++ signature */
        lb20a: bool = True
        # bool lb21 = true;    /* original C++ signature */
        lb21: bool = True
        # bool lb21a = true;    /* original C++ signature */
        lb21a: bool = True
        # bool lb21b = true;    /* original C++ signature */
        lb21b: bool = True
        # bool lb22 = true;    /* original C++ signature */
        lb22: bool = True
        # bool lb23 = true;    /* original C++ signature */
        lb23: bool = True
        # bool lb23a = true;    /* original C++ signature */
        lb23a: bool = True
        # bool lb24 = true;    /* original C++ signature */
        lb24: bool = True
        # bool lb25 = true;    /* original C++ signature */
        lb25: bool = True
        # bool lb26 = true;    /* original C++ signature */
        lb26: bool = True
        # bool lb27 = true;    /* original C++ signature */
        lb27: bool = True
        # bool lb28 = true;    /* original C++ signature */
        lb28: bool = True
        # bool lb28a = true;    /* original C++ signature */
        lb28a: bool = True
        # bool lb29 = true;    /* original C++ signature */
        lb29: bool = True
        # bool lb30 = true;    /* original C++ signature */
        lb30: bool = True
        # bool lb30a = true;    /* original C++ signature */
        lb30a: bool = True
        # bool lb30b = true;    /* original C++ signature */
        lb30b: bool = True
        # LineBreakConfig(bool useUnicodeAnnex14 = false, std::string breakAfter = " \t{[(", std::string breakBefore = ".", bool lb2 = true, bool lb3 = true, bool lb4 = true, bool lb5 = true, bool lb6 = true, bool lb7 = true, bool lb8 = true, bool lb8a = true, bool lb9 = true, bool lb10 = true, bool lb11 = true, bool lb12 = true, bool lb12a = true, bool lb13 = true, bool lb14 = true, bool lb15a = true, bool lb15b = true, bool lb15c = true, bool lb15d = true, bool lb16 = true, bool lb17 = true, bool lb18 = true, bool lb19 = true, bool lb19a = true, bool lb20 = true, bool lb20a = true, bool lb21 = true, bool lb21a = true, bool lb21b = true, bool lb22 = true, bool lb23 = true, bool lb23a = true, bool lb24 = true, bool lb25 = true, bool lb26 = true, bool lb27 = true, bool lb28 = true, bool lb28a = true, bool lb29 = true, bool lb30 = true, bool lb30a = true, bool lb30b = true);    /* original C++ signature */
        def __init__(
            self,
            use_unicode_annex14: bool = False,
            break_after: str = " \t{[(",
            break_before: str = ".",
            lb2: bool = True,
            lb3: bool = True,
            lb4: bool = True,
            lb5: bool = True,
            lb6: bool = True,
            lb7: bool = True,
            lb8: bool = True,
            lb8a: bool = True,
            lb9: bool = True,
            lb10: bool = True,
            lb11: bool = True,
            lb12: bool = True,
            lb12a: bool = True,
            lb13: bool = True,
            lb14: bool = True,
            lb15a: bool = True,
            lb15b: bool = True,
            lb15c: bool = True,
            lb15d: bool = True,
            lb16: bool = True,
            lb17: bool = True,
            lb18: bool = True,
            lb19: bool = True,
            lb19a: bool = True,
            lb20: bool = True,
            lb20a: bool = True,
            lb21: bool = True,
            lb21a: bool = True,
            lb21b: bool = True,
            lb22: bool = True,
            lb23: bool = True,
            lb23a: bool = True,
            lb24: bool = True,
            lb25: bool = True,
            lb26: bool = True,
            lb27: bool = True,
            lb28: bool = True,
            lb28a: bool = True,
            lb29: bool = True,
            lb30: bool = True,
            lb30a: bool = True,
            lb30b: bool = True
            ) -> None:
            """Auto-generated default constructor with named params"""
            pass

    # inline void SetLineBreakConfig(LineBreakConfig& newConfig);    /* original C++ signature */
    def set_line_break_config(self, new_config: TextEditor.LineBreakConfig) -> None:
        """ set the line break configuration"""
        pass


####################    </generated_from:TextEditor.h>    ####################


####################    <generated_from:TextDiff.h>    ####################
#	TextDiff - A syntax highlighting text diff widget for Dear ImGui.
#	Copyright (c) 2024-2026 Johan A. Goossens. All rights reserved.
#
#	This work is licensed under the terms of the MIT license.
#	For a copy, see <https://opensource.org/licenses/MIT>.




#
#	Include files
#



#
#	TextDiff
#

class TextDiff:
    # TextDiff();    /* original C++ signature */
    def __init__(self) -> None:
        """ constructor"""
        pass

    # specify options
    # inline void SetSideBySideMode(bool flag);    /* original C++ signature */
    def set_side_by_side_mode(self, flag: bool) -> None:
        pass
    # inline bool GetSideBySideMode() const;    /* original C++ signature */
    def get_side_by_side_mode(self) -> bool:
        pass
    # inline void SetTabSize(size_t value);    /* original C++ signature */
    def set_tab_size(self, value: int) -> None:
        pass
    # inline size_t GetTabSize() const;    /* original C++ signature */
    def get_tab_size(self) -> int:
        pass
    # inline void SetLineSpacing(float value);    /* original C++ signature */
    def set_line_spacing(self, value: float) -> None:
        pass
    # inline float GetLineSpacing() const;    /* original C++ signature */
    def get_line_spacing(self) -> float:
        pass
    # inline void SetWordWrapEnabled(bool value);    /* original C++ signature */
    def set_word_wrap_enabled(self, value: bool) -> None:
        pass
    # inline bool IsWordWrapEnabled() const;    /* original C++ signature */
    def is_word_wrap_enabled(self) -> bool:
        pass
    # inline void SetShowWhitespacesEnabled(bool value);    /* original C++ signature */
    def set_show_whitespaces_enabled(self, value: bool) -> None:
        pass
    # inline bool IsShowWhitespacesEnabled() const;    /* original C++ signature */
    def is_show_whitespaces_enabled(self) -> bool:
        pass
    # inline void SetShowSpacesEnabled(bool value);    /* original C++ signature */
    def set_show_spaces_enabled(self, value: bool) -> None:
        pass
    # inline bool IsShowSpacesEnabled() const;    /* original C++ signature */
    def is_show_spaces_enabled(self) -> bool:
        pass
    # inline void SetShowTabsEnabled(bool value);    /* original C++ signature */
    def set_show_tabs_enabled(self, value: bool) -> None:
        pass
    # inline bool IsShowTabsEnabled() const;    /* original C++ signature */
    def is_show_tabs_enabled(self) -> bool:
        pass
    # inline void SetShowScrollbarMiniMapEnabled(bool value);    /* original C++ signature */
    def set_show_scrollbar_mini_map_enabled(self, value: bool) -> None:
        pass
    # inline bool IsShowScrollbarMiniMapEnabled() const;    /* original C++ signature */
    def is_show_scrollbar_mini_map_enabled(self) -> bool:
        pass
    # inline void SetLanguage(const TextEditor::Language* language);    /* original C++ signature */
    def set_language(self, language: TextEditor.Language) -> None:
        pass
    # inline const TextEditor::Language* GetLanguage() const;    /* original C++ signature */
    def get_language(self) -> TextEditor.Language:
        pass
    # inline void SetColors(ImU32 ac, ImU32 dc);    /* original C++ signature */
    def set_colors(self, ac: ImU32, dc: ImU32) -> None:
        pass

    # inline void SetPalette(const TextEditor::Palette& newPalette);    /* original C++ signature */
    def set_palette(self, new_palette: TextEditor.Palette) -> None:
        pass
    # inline const TextEditor::Palette& GetPalette() const;    /* original C++ signature */
    def get_palette(self) -> TextEditor.Palette:
        pass

    # inline void SetFocus();    /* original C++ signature */
    def set_focus(self) -> None:
        """ programmatically set focus on the editor"""
        pass

    # void SetText(const std::string_view& left, const std::string_view& right);    /* original C++ signature */
    def set_text(self, left: str, right: str) -> None:
        """ specify the text to be compared (using UTF-8 encoded strings)"""
        pass

    # void Render(const char* title, const ImVec2& size=ImVec2(), ImGuiChildFlags childFlags=0, ImGuiWindowFlags windowFlags=ImGuiWindowFlags_NoMove);    /* original C++ signature */
    def render(
        self,
        title: str,
        size: Optional[ImVec2Like] = None,
        child_flags: ImGuiChildFlags = 0,
        window_flags: Optional[ImGuiWindowFlags] = None
        ) -> None:
        """ render text diff in a Dear ImGui context
         note: if you overwrite windowFlags to for instance add ImGuiWindowFlags_NoSavedSettings
         ensure you keep the default as it is required for the diff widget
         - ImGuiWindowFlags_NoMove to ensure mouse drag event are passed to the diff widget

        Python bindings defaults:
            If any of the params below is None, then its default value below will be used:
                * size: ImVec2()
                * windowFlags: ImGuiWindowFlags_NoMove
        """
        pass

####################    </generated_from:TextDiff.h>    ####################

# </litgen_stub> // Autogenerated code end!
