name: android

# Builds _example_integration for Android

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Checkout submodules
      run: git submodule update --init --recursive

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

#    - name: Setup interactive tmate session
#      uses: mxschmitt/action-tmate@v3

    - name: invoke cmake to create gradle / android studio project
      # This will create the project
      # build_android/hello_imgui_demodocking_AndroidStudio
      run: |
        cd _example_integration
        mkdir -p external
        cd external
        ln -s ../../ imgui_bundle
        cd ..
        mkdir build_android
        cd build_android
        export ANDROID_HOME=/usr/local/lib/android/sdk
        ../external/imgui_bundle/external/hello_imgui/hello_imgui/tools/android/cmake_arm-android.sh ..

    - name: gradlew build
      # This will build for all android architectures
      run: |
          export ANDROID_HOME=/usr/local/lib/android/sdk
          cd _example_integration/build_android/imgui_bundle_example_integration_AndroidStudio
          ./gradlew build
