# CMake functions to simplify the creation of demo apps using imgui_bundle
# Those are convenience functions, mostly used in the C++ and in the tutorials.

function(ibd_add_demo_cpp)
    # Creates an app using imgui_bundle_add_app, and link it with demo_utils
    # Usage:
    #     ibd_add_demo_cpp(demo_name demo_file_1.cpp demo_file_2.cpp)
    set(args ${ARGN})
    list(GET args 0 demo_name)

    # Only use a custom {demo_name}_assets/ folder if it exists.
    # Otherwise, no extra assets beyond the core imgui_bundle_assets/ (bundled automatically).
    # Demos needing demos_assets/ should add it explicitly via hello_imgui_bundle_assets_from_folder().
    if (EXISTS ${CMAKE_CURRENT_LIST_DIR}/${demo_name}_assets)
        message(STATUS "ibd_add_demo_cpp: ${demo_name} uses custom assets: ${demo_name}_assets/")
        imgui_bundle_add_app(${args} ASSETS_LOCATION ${CMAKE_CURRENT_LIST_DIR}/${demo_name}_assets)
    else()
        imgui_bundle_add_app(${args})
    endif()
    if(MSVC)
        hello_imgui_msvc_target_set_folder(${demo_name} demos_cpp)
    endif()
    target_link_libraries(${demo_name} PUBLIC demo_utils)
endfunction()

function(ibd_add_single_file_demo_cpp demo_cpp_file optional_prefix)
    # Creates a demo app
    # Usage:
    #     ibd_add_single_file_demo_cpp(demo_file.cpp)
    # or
    #    ibd_add_single_file_demo_cpp(demo_file.cpp prefix_)
    get_filename_component(demo_name "${demo_cpp_file}" NAME_WE)
    ibd_add_demo_cpp(${optional_prefix}${demo_name} ${demo_cpp_file})
endfunction()

function(ibd_add_auto_demo demo_cpp_file optional_prefix)
    # Creates a demo app, and provides main() automatically
    # Usage:
    #     ibd_add_auto_demo(demo_file.cpp)
    # (demo_file.cpp should provide a function named according to the containing file, e.g. `void demo_file()`)
    get_filename_component(demo_cpp_file "${demo_cpp_file}" NAME)
    get_filename_component(demo_name "${demo_cpp_file}" NAME_WE)
    ibd_add_demo_cpp(${optional_prefix}${demo_name} ${demo_cpp_file})

    # Read the contents of the cpp file
    file(READ "${demo_cpp_file}" demo_cpp_file_content)

    # If the cpp file does not contain a main function, provide it.
    # The regex requires `int main(` at the start of a line (after a newline
    # and optional indentation), so it does not trip on the substring
    # appearing inside a string literal or a comment (e.g. a demo that
    # embeds C++ sample text containing the line `int main() {`).
    #
    # NOTE: double-quoted string is intentional — CMake's regex engine does
    # not treat `\n` / `\t` as escapes, but double-quoted CMake strings turn
    # `\n` and `\t` into a real newline and tab byte before the regex sees
    # them. Using bracket-string [[...]] here would keep `\n` as literal
    # `\n` (backslash + n) and never match real newlines in the file.
    if (NOT "${demo_cpp_file_content}" MATCHES "\n[ \t]*int +main *\\(")
        message(STATUS "${demo_cpp_file} does not contain a main function, adding it!")
        set(main_file ${CMAKE_CURRENT_BINARY_DIR}/${demo_cpp_file}.autogenerated.cpp)
        configure_file(${demos_cpp_folder}/_auto_main/_auto_main.cpp.in ${main_file})
        target_sources(${demo_name} PRIVATE ${main_file})
    endif()

    if(EMSCRIPTEN)
        # Preload this demo's own source files so the "Show source" toggle
        # can read them at runtime in the browser. ReadCppCode/ReadPythonCode
        # look under /demos_cpp/ and /demos_python/ in the virtual FS.
        # The big `demo_imgui_bundle` launcher preloads the whole tree elsewhere;
        # standalone demos only need their own pair.
        set(_ibd_src_cpp ${demos_cpp_folder}/${demo_cpp_file})
        if(EXISTS ${_ibd_src_cpp})
            target_link_options(${demo_name} PRIVATE
                "SHELL:--preload-file ${_ibd_src_cpp}@/demos_cpp/${demo_cpp_file}"
            )
        endif()
        set(_ibd_src_py ${demos_cpp_folder}/../demos_python/${demo_name}.py)
        if(EXISTS ${_ibd_src_py})
            target_link_options(${demo_name} PRIVATE
                "SHELL:--preload-file ${_ibd_src_py}@/demos_python/${demo_name}.py"
            )
        endif()
    endif()

endfunction()

function(ibd_add_this_folder_demos optional_prefix)
    # Creates demo apps for all cpp files in the current folder
    FILE(GLOB demo_cpp_files *.cpp)
    FOREACH(demo_cpp_file ${demo_cpp_files})
        ibd_add_single_file_demo_cpp(${demo_cpp_file} "${optional_prefix}")
    ENDFOREACH()
endfunction()

function(ibd_add_this_folder_auto_demos optional_prefix)
    # Creates demo apps for all cpp files in the current folder, and provide a main for them
    FILE(GLOB demo_cpp_files *.cpp)
    FOREACH(demo_cpp_file ${demo_cpp_files})
        ibd_add_auto_demo(${demo_cpp_file} "${optional_prefix}")
    ENDFOREACH()
endfunction()


function(ibd_add_this_folder_as_demos_library)
    file(GLOB sources *.cpp)
    get_filename_component(folder_name "${CMAKE_CURRENT_LIST_DIR}" NAME_WE)
    set(demos_library_name ${folder_name})
    add_library(${demos_library_name} ${sources})
    target_link_libraries(${demos_library_name} PRIVATE imgui_bundle)
    target_link_libraries(${demos_library_name} PUBLIC demo_utils)
    target_compile_definitions(${demos_library_name} PRIVATE IMGUI_BUNDLE_BUILD_DEMO_AS_LIBRARY)
endfunction()
